### ISSUE TITLE
LTPA sign on

### ISSUE THREAD

**Issue by windgaucho** [markusberg/ltpa#1]
Hello and sorry if this is no te correct place to ask.

I want to validate in a domino server using ltpa toke, is this possible with this library?
Can you please point me in the right direction about how the validation could work?

Thanks in advance.

**Comment by markusberg** [comment]
Luis,

this is the right place to ask.

Yes, if you have a Domino-server you can use this library to generate tokens for access to the Domino server over the Domino Data Services API. In order for this library to work, you’ll need to extract your server key first. The basic usage is detailed in the README.md. 

Does that answer your question? If not, please provide more detailed information about your intended usage.
—
best regards
Markus Berg

**Comment by windgaucho** [comment]
Markus,

Thank you for your response.

Yes I have a Domino Server and extracted the LTPA_DominoSecret key, is this key wich your are referring?

I am a lotus notes developer and now I built a react.js application using an express back end server, this application also consume some notes data.

I would like to use lotus domino as a single sign on for this app and all my futures react/express applications and I don't know how to authenticate the users between my new app and lotus domino, can you point me in the right direction?

Thank you !!

Luis

**Comment by windgaucho** [comment]
Hello Markus,

Sorry for my previous notes security newbie question.

The servers administrator guy has installed two test servers and configured the web SSO document with ltpa.
He give to me the secret key.

If I am not wrong, in order to test this library, I must connect from the browser to the domino server using my credentials (user name and password).
From there I am able to run my test node express server to test this library? or how it would be?

Thanks in advance,

Luis

**Comment by markusberg** [comment]
Luis,

yes, in order to test the library you should first make sure that you can access the Domino Data Services API, preferably from a browser. Maybe if I explain the way I've used the library, it'll help you to understand?

We have a large-ish investment in XPages-applications where everything is handled by the Domino servers (auth/autz, presentation, data, etc.). I've now started to replace parts of those applications with modules written in node.js and angular.js, but still using Domino as a database backend (only accessed by our node.js middleware, and never by our angular front-end). This is completely transparent to the user, and my new module is mounted in-tree by way of an apache proxy that sits in front of our Domino and node.js servers.

```
xpages.example.com
/about
/docs
/new
```

The `/about`, and `/docs` routes are proxied to the Domino server and are handled by the old XPages framework, but when a user accesses the `/new` route, the request is proxied to the node.js server, and the new angular application is served. The `/new` module recognizes the LtpaToken cookie already set by the XPages framework, and is able to validate it as being authentic because it is signed with our secret key (the same key that the `ltpa` module has access to). The `/new` module also refreshes the cookie on all responses so the user session is kept alive.

The fact that the `/new` module can verify the validity of the LtpaToken means that we also know the Distinguished Name (DN) of the user accessing the site, because the DN is part of the LtpaToken.

 / Markus

**Comment by windgaucho** [comment]
Markus,
Thank you very much for your detailed answer!!

We have too, large xPages applications but we never have set the Ltpa token inside it, so my question now will be, can I use this library directly with my domino server? I am traying to figure out how to use or may be how the Ltpa token is send by the domino server....

Nevertheless, I could succesfully login with my credentials into my domino server using express. The server return the Request DomAuthSessId cookie, so I can send the cookie in all my requests.

I don't know if it last is a valid way but it works.

Thank you again!!

Luis

**Comment by markusberg** [comment]
I've never used the DomAuthSessId cookie, so I can't help you there. I just either verify and forward the user-provided LtpaToken cookie to the Domino server, or I generate a new cookie based on what user I need to access the Domino server as.

Good luck.

 / Markus

**Comment by windgaucho** [comment]
Thank you !!

I 've never used DomAuthSessId cookie too. I am just saying that I could successfully login into my domino server and now I am trying to use the LtpaToken but I can't get it to work.

After my successful login, how can I get the LptaToken? In your first example I am getting an error in the following line:
let ltpaToken = ltpa.refresh(req.cookies.LtpaToken, "example.com");

because LtpaToken is undefined.

And in the second example, I am generating the token with my user name (already logged in the domino server), but when I execute the request to my DAS service I am getting the login form as a result and I am already logged to my server.
What would be the problem?

Thank you in advance!!

Luis

**Comment by markusberg** [comment]
Bad news, I've looked up some of the documentation for the DomAuthSessId cookie that your Domino server is setting, and that is unfortunately a separate standard from the primitive LtpaToken that my library supports:
[ftp://ftp.software.ibm.com/software/integration/datapower/library/prod_docs/Misc/UnderstandingLTPA-v1.pdf](url)

**Comment by markusberg** [comment]
... it could also be a mis-configuration on the Domino server, as is discussed in this forum thread:
[http://www-10.lotus.com/ldd/nd6forum.nsf/DateAllFlatweb/784a117b188dba1d852573d800605924?OpenDocument](url)

Regardless, my library does not decode/encode DomAuthSessId cookies. Sorry.

**Comment by windgaucho** [comment]
Markus, thank you very much for your time and try to help me, I really appreciate it!!

I think that my problem is more related to the second link that you has provided me. I will check it out with  the domino server administrator and see if there is a problem with the Session-based authentication. I will check how is the server configuration, I mean if it is for single server (that send the DomAuthSessId) or multiple server (that send the expected LtpaToken).

The domino server administrator has installed and configured two domino servers, so  that I can perform tests with the SSO using the LtpaToken key. I have read your second link and this one:
[http://www-01.ibm.com/support/docview.wss?uid=swg27003558](url)
and I think that there is a problem with the configuration. 

We have configured the two servers following this document:
[https://www.ibm.com/support/knowledgecenter/SSKTMJ_9.0.1/admin/conf_creatingawebssoconfigurationdocument_t.html](url)

But like I say, when I sign in to the server using my credentials (name and password) the domino server send me the DomAuthSessId and not the LtpaToken as expected.

**Comment by windgaucho** [comment]
Hello Markus,

The problem is resolved and now your library works !!

The SSO configuration document was the problem in our case because it was in conflict with an already existent SSO configuration document for the ibm sametime.
We resolved the conflict and now all works as expected!! 
The only thing that not work for now is if we use the server ip address for access to the DAS service, it not work, but if we use the dns server name works ok !!

Thank you very much for your support and for this library !!

Best regards,

Luis

**Comment by markusberg** [comment]
That's fantastic news, Luis. Good luck!

 / Markus
