### ISSUE TITLE
Is this LTPAv2

### ISSUE THREAD

**Issue by EwanSadie** [markusberg/ltpa#2]
This seems to be different than the way Samir does it in Java.  The Java code works for me.
Will you be extending this code to be LTPAv2 as well?
https://sites.google.com/site/samiraraujo/projects/ltpa-token-factory

**Comment by markusberg** [comment]
This is only LTPA1. I have no plans to extend the library further as I no longer work with IBM Domino (thankfully). 

When I developed it, our Domino servers only used LTPA1, so that's the reason behind this limitation.
