### ISSUE TITLE
Crypto deprecated module

### ISSUE THREAD

**Issue by taoufiqi** [markusberg/ltpa#26]
Hi Markus,
I try to use your module and I faced an issue with NPM. Crypto is no longer used and it's now an internal node module.

I'm not a good Nodesjs developper, can you tell me how to fix the error please. The same for Buffer, i didn't see any import of this type in your code.

Regards,

**Comment by markusberg** [comment]
Hi. What version of NodeJs are you running? I haven't tested it on v18 yet.

I'm running it on NodeJS v16 in several production systems without issue.
