### ISSUE TITLE
Validity period calculation standard as option

### ISSUE THREAD

**Issue by Notice-Jeroen-Meijer** [markusberg/ltpa#7]
May I suggest to add an option (i.e. by setting the validity period to 0, or by a new setting) to use the expire datetime as stated in the token? I'd be happy to do this as a PR, but in all honesty, it's probably two lines of code, so faster this way.

Thank you for this module :-)

EDIT: i.e.
line 138 in index.ts
```
  if ((validity == 0 ? timeExpiration : timeCreation + validity + gracePeriod * 2) < now) {
```

**Comment by markusberg** [comment]
This is a great suggestion. It's been a while since I looked at the actual code, but there's some weird behaviour there. Why doesn't my code respect the provided expiration date? Explicitly so. Weird. I was probably trying to be "extra helpful".

I'll look this over, and publish a new version. This will likely require a major version bump since the behaviour will change.

**Comment by Notice-Jeroen-Meijer** [comment]
Your thinking was probably to rely the least possible on the token info. In my use case I have a few long living tokens used not by end users but other servers fetching data.

I mildly disagree with a major bump, especially if you make the new behavior a new setting (added functionality) which would be a minor. However, if you go by the standard and not use the validity setting at all but simply use the end time as stated in the token, I agree. Then of course my suggestion above should be changed to 
```
if (timeExpiration + gracePeriod * 2 < now) {
```
I've fixed it for myself the brute way, but yes a new version would be much appreciated

**Comment by markusberg** [comment]
My plan is something along these lines:
- respect the provided expiration date when validating tokens. Is there ever a reason not to do this?
- add an optional parameter to ltpa.refresh() to make it use the same validity as the provided token

If I skip the first one, there will be no need to bump the major version. I'll do that, and make a minor release. Then I can put some more thought into the api of the next major version.

**Comment by Notice-Jeroen-Meijer** [comment]
Forgive for the entirely selfish, personal opinion.

- If you skip bullet one for now, if even optional, it's moving up the real, ahem, my real issue to a major release. That OK (of course it is :-) ), but, well.......
- Two, IMHO, is entirely irrelevant. The server (AKA this code) is the boss of the validity window, and borrowing it from the old token serves no purpose and is in a way handing over control to another issuer. Why even do that. I might be missing the background of this idea.
Thanks for considering

**Comment by markusberg** [comment]
Sorry, I think I was over analyzing your use-case. The thing is that a validity setting of 0 will make little sense when generating new tokens. Since that is the case, it's probably safe to assume that no-one is doing that. 

I'll add your feature suggestion as originally suggested, and push a new minor version.

**Comment by markusberg** [comment]
Ok, so I'm implementing this, and I'm not comfortable doing this through the validity-variable. It doesn't feel intuitive at all. I'd really rather just add a new setting. 

Something like setStrictExpirationValidation(strict: boolean)

**Comment by Notice-Jeroen-Meijer** [comment]
Completely agree, and in you shoes I'd do the same. If you leave the default behavior as it is now, I'd say only a minor bump is warranted. In any case: thank you for the code and considering this change.

**Comment by markusberg** [comment]
Alright. Version 1.1.0 published with new setStrictExpirationValidation()-functionality. The Readme.md is also updated with improved api documentation.

I refactored the code quite extensively yesterday, but the api is the same except for the aforementioned addition. Code Coverage is at 100%, and all the tests are passing. Please let me know if there are any issues.
