### ISSUE TITLE
Signature compatibility (possible issues)

### ISSUE THREAD

**Issue by Notice-Jeroen-Meijer** [markusberg/ltpa#8]
Can I ask if you have tried not only login/auth on node but also cross compatibility with Domino? In this version tokens generated by Domino do not authenticate it seems. It does work with it's own tokens, suggesting a problem with the hash/signature (which is the error on the console too).

I am fairly sure this was not the case before the last release; I did test with existing (generated by Domino) tokens.

Error on my end is always possible of course, but I triple checked the secret and through single stepping that that secret is actually used.

**Comment by markusberg** [comment]
Well that's disturbing. No sorry, I don't have access to any Domino-servers. Could you try reverting to the old version, and see if you experience the same problems?

What is the specific error thrown?

**Comment by Notice-Jeroen-Meijer** [comment]
"Ltpa Token signature doesn't validate"

No worries, it's not in production at this moment. I could generate a new (as in, unused in production) secret and a long living token if you want.

**Comment by markusberg** [comment]
I've added regression testing of the known tokens that I have access to, and I'm unable to reproduce this issue. Have you tried reverting to version 1.0.4 to see if that version exhibits the same problems?

**Comment by Notice-Jeroen-Meijer** [comment]
I didn't revert back, but I tried before updating with the same secret/tokens and it worked.

Thanks for trying. I'll have a bunch of other shots at it and report back. It's on my plate for the moment :-)

**Comment by Notice-Jeroen-Meijer** [comment]
I can confirm my use case works on 1.0.4, not the current release.  
Description:
- login on domino server (SSO configured)
- extract token from storage area of a web page when logged in
- extract key from SSO document (in base64 format)
- execute the following code in both 1.0.4 and 1.1.0
```
ltpa.setValidity(315360000); // 10 year (just to avoid timing issues
ltpa.setSecrets({
    "ploink.lan": "base64secret",
})
ltpa.validate("base64token", "ploink.lan")
```
On 1.1.0 it fails with
```
...\node_modules\ltpa\dist\Token.class.js:87
            throw new Error("Ltpa Token signature doesn't validate");
```
However, this code works on both versions
```
ltpa.setValidity(315360000); // 10 year (just to avoid timing issues
ltpa.setSecrets({
    "ploink.lan": "222222222222222222222222222=",
})
const userNameBuf = ltpa.generateUserNameBuf("BozoTheClown")
const ltpaToken = ltpa.generate(userNameBuf, "ploink.lan")
ltpa.validate(ltpaToken, "ploink.lan")
```
It must be an issue calculating the digest. You have to believe me on the validity of the secret and token. I'll try to find the problem too.
 [edit for typo]

**Comment by markusberg** [comment]
Well that's disappointing. Probably related to my refactoring. I'll revert to 1.0.4, add the strict expiration validation, and republish as 1.2.0.

**Comment by Notice-Jeroen-Meijer** [comment]
OK. Since you don't have access to a domino server, I'll try to figure out what's going on as it was a neat refactoring 👍 . But with a slightly lower priority now. Thanks!

**Comment by markusberg** [comment]
I've done git-surgery on my repo, and have undone all of the refactoring. I've kept the strict expiration validation, the documentation updates, and the package-updates, and most of the changes to the test suite.

I've published it as 1.2.0, but I realize now that 1.1.1 might have been better.

Keeping fingers crossed.

**Comment by Notice-Jeroen-Meijer** [comment]
eeeew, git-surgery! I'll give it a spin soon.

**Comment by markusberg** [comment]
Is everything working ok with version 1.2.0? Can I close this issue?

**Comment by Notice-Jeroen-Meijer** [comment]
Sorry, yes. I had kept it open as I wanted to give you feedback on the refactoring issue when I had the time (and inclination ;-) ). I'll try to remember it. Closing and will comment on this issue if I find something.
